### ISSUE TITLE
Eclipse/DDT support

### ISSUE THREAD

**Issue by mathstuf** [trentforkert/cmake#16]
We should set the `ECLIPSE_EXTRA_NATURES` global property to get D support with the Eclipse extra generator for [DDT](https://github.com/bruno-medeiros/DDT). A quick search shows "org/dsource/ddt/ide/core/DeeNature.java", so the nature should be `org.dsource.ddt.ide.core.DeeNature` [here](https://github.com/trentforkert/cmake/blob/d_support3/Source/cmExtraEclipseCDT4Generator.cxx#L54-75).

**Comment by trentforkert** [comment]
Done in 129987070b2a6aa80281af4e674bcc44c7bc1aa1.

Although, I will say that I didn't notice a difference between having it and not having it in my (limited) tests.

**Comment by mathstuf** [comment]
I don't use Eclipse, but adding the Android nature gives you the UI designer, the XML editors, and other stuff. Whatever DDT adds should be provided here as well (there also might be other natures which are needed).
