### ISSUE TITLE
DDeps errors out

### ISSUE THREAD

**Issue by mathstuf** [trentforkert/cmake#19]
I'm getting errors such as:

```
DDeps Warning: /home/boeckb/code/other/lang-d/proj-derelict/DerelictGLES/source/derelict/gles/eglext.d could not be found by the name "" in any of the following directories:
    ../source
    /home/boeckb/misc/root/gdc/include/d
Ensure your import directories are correct,and that the module name matches the filename.
/home/boeckb/code/other/lang-d/proj-derelict/DerelictGLES/source/derelict/gles/eglext.d will be not be scanned for dependencies.
```

from the latest code.

**Comment by trentforkert** [comment]
Hmm... I've got a hunch something isn't handling relative paths correctly somewhere along the line. Will investigate.

Your code should still compile in spite of this warning, though. Is this actually halting compilation, or just spitting messages at you?

**Comment by mathstuf** [comment]
It compiles, but Ninja is (or at least seems so; it complains about circular dependencies) hopelessly confused on subsequent runs.

**Comment by trentforkert** [comment]
Well, my hunch was completely wrong, but I did manage to track down and fix these bugs, I think. I can't reproduce those errors anymore, anyway.

**Comment by mathstuf** [comment]
Thanks! I'll try and test it out tomorrow (not sure how much time I'll have in the evening).

**Comment by mathstuf** [comment]
Looks good here. Thanks.

**Comment by mathstuf** [comment]
I wonder if I wasn't using an old build when I tried earlier:

```
DDeps Warning: /home/boeckb/code/other/group-games/group-abagames/mu-cade/src/src/abagames/util/ode/odeactor.d could not be found by the name "abagames/util/ode/odeactor" in any of the following directories:
Ensure your import directories are correct,and that the module name matches the filename.
/home/boeckb/code/other/group-games/group-abagames/mu-cade/src/src/abagames/util/ode/odeactor.d will be not be scanned for dependencies.
```

**Comment by trentforkert** [comment]
I have yet to manage to reproduce this.

Can you confirm that you are on branch `d_support3`?

**Comment by mathstuf** [comment]
So I debugged this some more. I have `-fdebug` on the command line, but it looks like DDeps is expecting `-fdebug=VALUE` and when the parser sees that it is missing a value, it bails out before it gets to the `-I` modules, but there's no error checking, so it then complains about not finding the module in the paths it didn't look at. Seems to come from `Modules/Compiler/GNU-D.cmake`'s setting of `CMAKE_D_FLAGS_DEBUG_INIT` to `-g -fdebug`.
