### ISSUE TITLE
Q: What is the status of the project?

### ISSUE THREAD

**Issue by snosov1** [trentforkert/cmake#23]
Hi!

This project seems quite solid in terms of features and quality of implementation. Do you have plans to merge it upstream? When could this happen? Thanks!

**Comment by trentforkert** [comment]
> Do you have plans to merge it upstream?

Yes, eventually.

> When could this happen?

A merge upstream is blocked by a handful of other things:
- I don't want to merge upstream until I know shared library support is working across at least Linux, OS X, and Windows. This might require language changes, and I won't know for sure if they effect my parser until they are finalized and/or implemented, though there has been more progress on this recently
- I currently don't have many tests, especially for the pieces that are most likely to be broken or break in future (i.e., my parser)
- Documentation could stand some improvement
- Any bugs found by the (to be written) tests will need to be fixed
- Modules for other D things may need to be written (or pulled from elsewhere) if there is functionality we want to include

Additionally, my time has been taken up by other projects recently, and this works for me without the above. However, you are the fourth person to either mention or ask about this project recently, so I should probably find some time to work on things over the next couple of days.

**Comment by snosov1** [comment]
> Additionally, my time has been taken up by other projects recently, and this works for me without the above. However, you are the fourth person to either mention or ask about this project recently, so I should probably find some time to work on things over the next couple of days.

Thanks!
